home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    path('home/', views.home, name='home'),
    path('homeAfterLogin/', views.homeAfterLogin, name='homeAfterLogin'),
    path('movies/', views.movies, name='movies'),
    # path('movies/api/movies/<str:movie>/', views.retrieve, name='retrieve'),
    path('movies/data/', views.data, name='data'),
]

playlist/urls.py
from django.urls import path
from . import views

app_name = 'playlist'

urlpatterns = [
    path('', views.playlist, name='playlist'),

]

productivity/urls.py
from django.urls import path
from .views import activity, data

app_name = 'productivity'

urlpatterns = [
    path('productivity-tracker/', activity, name='activity'),
    path('productivity-tracker/activity-data', data, name='activity_data'),
]

tk2proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('productivity.urls')),
    path('quotes/', include('quotesgen.urls')),
    path('playlist/', include('playlist.urls')),
    path('', include('login.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Bootstrap CSS -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}" />
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block link %}
  {% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tracker.css' %}" />
  <title> Rest your soul. </title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'landingPage' %}">
      <div class="title" style="font-family: 'Abril Fatface', cursive;"> rest your <span> soul. </span> </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'quotesgen' %}"> QUOTES </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'playlist:playlist' %}"> PLAYLIST </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'productivity:activity' %}"> PRODUCTIVITY</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies' %}"> TOP SERIES</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"> LOG OUT</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'js/productivity.js' %}"></script>
  {% block content %}
  {% endblock %}

  {% block footer %}
    <div class="footer">
      <p id="footer"> &copy; Copyright 2020 Group G-1 <span>Rest Your Soul</span>. All Rights Deserved.
      </p>
    </div>
  {% endblock %}

  {% block js %}
  {% endblock %}
</body>

</html>

templates/tracker.html
{% extends 'base.html' %}
{% block content %}

<div class="container py-4">
    <h1 class="toDo_title">Things <span>to-do</span></h1>
    <p id="better"><i>that make you <strong>feel better</strong></i></p>
    
    {% if user.is_authenticated %}
    <Form method="POST" class="row my-5" id="form">
        {% csrf_token %}
        <div class="toDo_insert">
            {{ form.activity }}
        </div>
        <button type="button" class="btn toDo_add" id="toDo_button">Add</button>
    </Form>
    {% endif %}

    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}

    <div class="toDo_list">
        {% if user.is_authenticated == False %}
        <p style="text-align: center;"><a href="/login">Login</a>
            first, so you can share your activity</p>
        <!-- <p style="text-align: center;"><a href="/login">Login</a>
         first, so you can check these to do lists</p> -->
        {% endif %}
        <div class="flex-container" id="list_activity">
            <div class="btn-group-toggle " data-toggle="buttons">
                <label class="btn checkmark active">
                    <input type="checkbox" autocomplete="off"><span class = "checkmark" id="centang"></span>
                </label>
            </div>   
            <div class="card list">
                <h5 class="activity col-10">tidur</h5>   
            </div>
        </div>

        <div id="activity-container">
        </div>
        

    </div>

    <div class="card quotes">
        <div class="card-body">
          <h5 class="card-title"><i>"Part of the <strong>healing</strong> process is 
                <strong>sharing</strong> with other people who care"</i></h5>
          <p class="card-text"><hr>- Jerry Cantrell -</p>
        </div>
    </div>

    <div class ="row">
        <div class="col-lg-6">
            <div class="foto-pusing"></div>
        </div>
        <div class="col-lg-6">                    
            <div class="semangat">
                <p>Have a wonderful day !
                    <!-- <br><b> {{name}} </b>! -->
                </p>
            </div>
        </div>
    </div>
    
</div>

{% endblock content %}